name: Create Release Draft

on:
  push:
    tags:
      - "v*"

  workflow_dispatch:


jobs:
  release:

    runs-on: ubuntu-latest
    permissions:
      contents: write
      repository-projects: write

    steps:

      - name: Checkout repo
        uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '22.14.0'

      - name: Install deps
        run: yarn --frozen-lockfile

      - name: Build + zip extensions
        run: yarn build:all

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: ${{ github.ref_name }}
          body: |
            Updates:
            Features:
            Fixes:
            New contributors:
          draft: true
          prerelease: false

      - name: Upload Chrome build to release
        id: upload-release-asset-chrome
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./builds/rao_chrome_${{ github.ref_name }}.zip
          asset_name: rao_chrome_${{ github.ref_name }}.zip
          asset_content_type: application/zip

      - name: Upload Firefox build to release
        id: upload-release-asset-firefox
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./builds/rao_firefox_${{ github.ref_name }}.zip
          asset_name: rao_firefox_${{ github.ref_name }}.zip
          asset_content_type: application/zip

      - name: Upload Edge build to release
        id: upload-release-asset-edge
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./builds/rao_edge_${{ github.ref_name }}.zip
          asset_name: rao_edge_${{ github.ref_name }}.zip
          asset_content_type: application/zip
